import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const plusJakartaSnans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "FoundTIK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${plusJakartaSnans.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
